#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
version: '2'
services:
  redis:
    image: redis:3.2
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis:/data

  postgres:
    image: postgres:10
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  superset:
    build:
      context: ../
      dockerfile: local_app/Dockerfile
    restart: unless-stopped
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_ICON: https://sacg.abase.com.br/static/media/imgSacG.45392291.png
      APP_ICON_WIDTH: 70
      APP_NAME: "SacgTest"
      APP_JWT_KEY: abc123
      APP_JWT_AUDIENCE: http://localhost
      APP_JWT_ROLE_NAME: Agenda
      EDUCAR_CONNECTION_USER: abc123
      EDUCAR_CONNECTION_PASSWORD: a
      EDUCAR_CONNECTION_HOST: abc123
      EDUCAR_CONNECTION_PORT: 123
      EDUCAR_CONNECTION_DATABASE: db123
      # If using production, comment development volume below
      SUPERSET_ENV: production
      # SUPERSET_ENV: development
    user: root:root
    ports:
      - 8088:8088
    depends_on:
      - postgres
      - redis
    volumes:
      # this is needed to communicate with the postgres and redis services
      - ./superset_config.py:/home/superset/superset/superset_config.py
      - ./mutator.py:/home/superset/superset/mutator.py
      - ./educar_connection.py:/home/superset/superset/educar_connection.py
      - ./educar_integracao.py:/home/superset/superset/educar_integracao.py
      - ./abase_security.py:/home/superset/superset/abase_security.py
      # this is needed for development, remove with SUPERSET_ENV=production
      - ../superset:/home/superset/superset

volumes:
  postgres:
    external: false
  redis:
    external: false
